### PR TITLE
Fix Github Actions tests

### PR DESCRIPTION
**Pull request by valeriupredoi**
## Changes to Github Action workflow files

- Renamed `.github/workflows/recipes.yml` to `.github/workflows/install-esmvaltool-run-recipes.yml` and changed:
  - changed job name for better readability
  - introduced nightly run (can turn it off if you deem it overkill)
  - changed to Python 3.9
  - install latest esmvaltool with mamba in the base environment
  - turned off local call to caching via and manual data download with `wget`
  - turned on auto download of data with ESMValCore's `pyesgf-client`
  - running only the warming stripes recipes since fluxcom needs OBS6 data that is unavailable for download
- Renamed `.github/workflows/ci.yml` to `.github/workflows/build-check-tutorial-site.yml` and changed nothing

## Problems:

- `recipe_test_fluxcom.yml` is not currently running since it needs OBS6 data
- probably not necessary to run GA tests on both Push and Pull?
- `python bin/lesson_check.py -s . -p ${PARSER} -r _includes/links.md -l -w` is currently returning a number of issues hence the lesson checker fails
- I'll open Issues for these, but for now this is ready to roll - unless @SarahAlidoost or @rswamina want to fix the `make` issues? You can reproduce the `make` issue by creating a ruby env and installing those gems like in the GA workflow file, then you can manually run the Python script

# Pull Request checklist

We appreciate your time and effort to improve the tutorial. Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution.

* * *

## Before you start

- [x] Read [CONTRIBUTING.md](https://github.com/ESMValGroup/tutorial/blob/master/CONTRIBUTING.md).
- [x] Create an [issue](https://github.com/ESMValGroup/tutorial/issues) to discuss your idea. This allows your contributions to be incorporated into the tutorial.

## Tasks

- [x] Give this pull request a descriptive title.

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *

Closes {Link to the corresponding issue}

### CODE REVIEW

**Comment by rswamina** [comment]
@valeriupredoi - Thanks for this. I am not completely sure I understand how Github Actions work so have a few questions. 

1. Over the next month, we expect significant changes to be made to th etutorial to keep up with v2.4 of ESMValTool. Will that affect the way Github Actions work?
2. For recipe_fluxcom , do we not support OBS6 datasets anymore?
3. Is it ok to ignore the lesson checker?

I'd be happy to approve the pul request and see if this works assuming the above are not problems. Let me know.

**Comment by valeriupredoi** [comment]
> @valeriupredoi - Thanks for this. I am not completely sure I understand how Github Actions work so have a few questions.

no problem, Ranjini, here's me answers:
 
>     1. Over the next month, we expect significant changes to be made to th etutorial to keep up with v2.4 of ESMValTool. Will that affect the way Github Actions work?

no, not the recipe runs GA test since that's already using the latest 2.4 in this PR; about the other test, the tutorial Jekyll checker, that's not dealing with any ESMValTool versioning from a functional point, but rather, with the way the tutorial is packaged with Jekyll and Ruby and the way the lessons are written in Markdown

> 
>     2. For recipe_fluxcom , do we not support OBS6 datasets anymore?

I don't know actually, I can't seem to find it in the main ESMValTool repo anymore

> 
>     3. Is it ok to ignore the lesson checker?

@SarahAlidoost is best to answer this

> 
> 
> I'd be happy to approve the pul request and see if this works assuming the above are not problems. Let me know.

Cheers, prob best if Sarah sees it too methinks? :beer:

**Review by SarahAlidoost — APPROVED** [review]
@valeriupredoi the changes look great, many thanks. I'll make issues for recipe fluxcom and `lesson_check`. Also, I am OK if we run the GA only on push and not pull_request.

**Comment by SarahAlidoost** [comment]
@rswamina thanks for your comment. 

> 2. For recipe_fluxcom , do we not support OBS6 datasets anymore?

We don't provide the data in this repository because the data needs registration, see [Cmorization lesson](https://esmvalgroup.github.io/ESMValTool_Tutorial/09-cmorization/index.html). 

> 3. Is it ok to ignore the lesson checker?

It depends on the details of the errors. If the errors are minor like the lengths of lines in the lesson, we can ignore them. So, whenever a pull request is made, we can check the details of the errors reported by GA.

**Comment by valeriupredoi** [comment]
cheers @SarahAlidoost I turned off the run on PRs (you can turn it on anytime); also removed commented out and obsolete syntax; have a looksee when you got time and if there's anything else for me to do please let me know :+1:

**Comment by SarahAlidoost** [comment]
> cheers @SarahAlidoost I turned off the run on PRs (you can turn it on anytime); also removed commented out and obsolete syntax; have a looksee when you got time and if there's anything else for me to do please let me know +1

Awesome and many thanks :+1:

**Comment by SarahAlidoost** [comment]
> @SarahAlidoost - I think I wrote this CMOR-ization script. The FLUXCOM data is Tier3 (can't be shared without permission). Also OBS6 because it wasn't part of any other project as such. Is this a problem? On JASMIN and MISTRAL we have access to share it with users who have access to our OBS directories and this is with permission from the data owners.

there is no problem with the tutorial regarding this script. We also explained about the data and how to access it in the lesson https://esmvalgroup.github.io/ESMValTool_Tutorial/09-cmorization/index.html.

**Pull request merged**
