### PR TITLE
Change chapter order after the addition of advanced topic chapters

### PR DESCRIPTION
**Pull request by rswamina**
# Pull Request checklist

We appreciate your time and effort to improve the tutorial. Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution.

* * *

## Before you start

- [x] Read [CONTRIBUTING.md](https://github.com/ESMValGroup/tutorial/blob/master/CONTRIBUTING.md).
- [x] Create an [issue](https://github.com/ESMValGroup/tutorial/issues) to discuss your idea. This allows your contributions to be incorporated into the tutorial.

## Tasks

- [x] Give this pull request a descriptive title.
- [x] If you are contributing to existing lesson materials, please make sure the content conforms to the `Lesson development` section in [CONTRIBUTING.md](https://github.com/ESMValGroup/tutorial/blob/master/CONTRIBUTING.md) and does not contain any spelling or grammatical errors.
- [ ] If you are making a new episode, please make sure the content conforms to the `Lesson organization` and `Lesson formatting` sections in [CONTRIBUTING.md](https://github.com/ESMValGroup/tutorial/blob/master/CONTRIBUTING.md) and does not contain any spelling or grammatical errors.
- [ ] Preferably Codacy checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why.
- [x] Preview changes on your machine before pushing them to GitHub by running `make serve`, alternatively `make docker-serve`. Please see the `Previewing your changes locally` section in [CONTRIBUTING.md](https://github.com/ESMValGroup/tutorial/blob/master/CONTRIBUTING.md) for installation instructions.
- [x] All code instructions have been tested.

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *

Closes {https://github.com/ESMValGroup/ESMValTool_Tutorial/issues/198}

### CODE REVIEW

**Review by Peter9192 — CHANGES_REQUESTED** [review]
Hi @rswamina thanks for making this PR! 

I did a few searches and I think you missed the following references: 

./09-cmorization.md:227:> > To learn more about writing a recipe, please refer to [Writing your own recipe](/05-preprocessor)
./09-cmorization.md:63:explained in the [previous episode](/08-development-setup).
./09-cmorization.md:749:  on [Contributing to ESMValTool](/08-development-setup).

For the next time, I think there is an alternative method to sort the episodes, where we discard the manual numbering of the file names, but instead provide a custom order in a configuration file (see https://github.com/ESMValGroup/ESMValTool_Tutorial/blob/master/_includes/manual_episode_order.html). I think that might be easier than having to modify all the internal references everytime.

**Comment by rswamina** [comment]
@Peter9192 - Have made the changes suggested. Also changed references to "previous chapter" etc. where possible. We should refer to chapter names and not reference them in the future. If you find anything else that needs fixing, let me know. Otherwise perhaps it can be merged.

**Comment by rswamina** [comment]
@Peter9192 : can you please approve and merge this so we can start testing? If you think anything else needs to be addressed, let me know.Thanks!

**Review by Peter9192 — APPROVED** [review]

**Comment by Peter9192** [comment]
Thanks @rswamina !

**Pull request merged**
