### PR TITLE
Simplified and added setup section 

### LINKED ISSUE #159: 'Using your own machine' should be first in the `setup.md`
**Is your feature related to a problem? Please describe.**
I'm imagining that most people will want to run through the tutorial on their own machine. As such, I think that the section 'Using your own machine' should come before the clusters in the `setup.md`.

### PR DESCRIPTION
**Pull request by gulcing**
# Pull Request checklist

We appreciate your time and effort to improve the tutorial. Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution.

## Before you start

- [x] Read [CONTRIBUTING.md](https://github.com/ESMValGroup/tutorial/blob/master/CONTRIBUTING.md).
- [x] Create an [issue](https://github.com/ESMValGroup/tutorial/issues) to discuss your idea. This allows your contributions to be incorporated into the tutorial.

## Tasks

- [x] Give this pull request a descriptive title.
- [x] If you are contributing to existing lesson materials, please make sure the content conforms to the `Lesson development` section in [CONTRIBUTING.md](https://github.com/ESMValGroup/tutorial/blob/master/CONTRIBUTING.md) and does not contain any spelling or grammatical errors.
- [ ] If you are making a new episode, please make sure the content conforms to the `Lesson organization` and `Lesson formatting` sections in [CONTRIBUTING.md](https://github.com/ESMValGroup/tutorial/blob/master/CONTRIBUTING.md) and does not contain any spelling or grammatical errors.
- [ ] Preferably Codacy checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why.
- [ ] Preview changes on your machine before pushing them to GitHub by running `make serve`, alternatively `make docker-serve`. Please see the `Previewing your changes locally` section in [CONTRIBUTING.md](https://github.com/ESMValGroup/tutorial/blob/master/CONTRIBUTING.md) for installation instructions.
- [ ] All code instructions have been tested.

Closes #159, #173

### CODE REVIEW

**Comment by LisaBock** [comment]
Thanks @gulcing for your contributions!
Could you please separate the different tasks you worked on in different pull request (e.g. one about the link checker and another for the cmorization episode). That would make the review easier. Thanks!

**Comment by rswamina** [comment]
@LisaBock - Is this PR to be completed?

**Comment by LisaBock** [comment]
> @LisaBock - Is this PR to be completed?

It seems to me that the changes in this PR is also part of other PRs (#319 and #333). @gulcing - Do you think we could remove this PR?

**Comment by gulcing** [comment]
sure @LisaBock, you're right

**Pull request closed without merging**
