### PR TITLE
Update episode 8 after testing with esmvaltool 2.6

### LINKED ISSUE #204: Review training material episode 8
**Episode 8: review**

https://esmvalgroup.github.io/ESMValTool_Tutorial/08-diagnostics/index.html

- How we indicate the pat to a script or recipe is not consistent between episodes:

We can find the recipe `recipe_python.yml` and the python script `diagnostic.py` in these directories:

```
path_to_ESMValTool/esmvaltool/recipes/examples/recipe_python.yml
path_to_ESMValTool/esmvaltool/diag_scripts/examples/diagnostic.py
```
For consistency with the previous episode, I would rather `cd ~/ESMValTool` and provide relative paths. (then we need to make sure we clone in the HOME area in the previous episode).

Such as:

We can find the recipe `recipe_python.yml` and the python script `diagnostic.py` in these directories:

```
cd ~/ESMValTool
ls esmvaltool/recipes/examples/recipe_python.yml
ls esmvaltool/diag_scripts/examples/diagnostic.py
```

- There is a typo (add s to preprocesor):

e.g. **Preprocesor-diagnostic interface**

to replace with

**Preprocessor-diagnostic interface**

- could we find a better word than "thing"?

**The first thing passed to the diagnostic via the cfg dictionary is a path to a file called settings.yml**

Maybe "The first element..."

**Extracting information needed for analyses**

Answer
path_to_recipe_output/run/map/script1/log.txt

Maybe remind the learners where to find this path in their config file. (and maybe in the config file, we should use
~/esmvaltool_output` (I mean here the outputs are quite small so it should not be an issue to store it in your HOME?).

And then rather say here:

`~/esmvaltool_output/run/map/script1/log.txt`

**Diagnostic computation**

3 different ways for reading netCDF are shown. A discussion on the pros and cons of each methods would be useful (memory usage, parallelism, etc.).

**Recording the provenance**

Provenance is stored in the W3C PROV XML format and also in an SVG file ...
I would suggest to add a link to W3C PROV XML such as [W3C PROV XML](https://www.w3.org/TR/prov-xml/)

### LINKED ISSUE #254: Update episode Writing your own diagnostic script to 2.6
check the lesson "episode Writing your own diagnostic script" and update it if needed.

### PR DESCRIPTION
**Pull request by SarahAlidoost**
# Pull Request checklist

We appreciate your time and effort to improve the tutorial. Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution.

* * *

## Before you start

- [x] Read [CONTRIBUTING.md](https://github.com/ESMValGroup/tutorial/blob/master/CONTRIBUTING.md).
- [x] Create an [issue](https://github.com/ESMValGroup/tutorial/issues) to discuss your idea. This allows your contributions to be incorporated into the tutorial.

## Tasks

- [x] Give this pull request a descriptive title.
- [x] If you are contributing to existing lesson materials, please make sure the content conforms to the `Lesson development` section in [CONTRIBUTING.md](https://github.com/ESMValGroup/tutorial/blob/master/CONTRIBUTING.md) and does not contain any spelling or grammatical errors.
- [x] If you are making a new episode, please make sure the content conforms to the `Lesson organization` and `Lesson formatting` sections in [CONTRIBUTING.md](https://github.com/ESMValGroup/tutorial/blob/master/CONTRIBUTING.md) and does not contain any spelling or grammatical errors.
- [x] Preferably Codacy checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why.
- [x] Preview changes on your machine before pushing them to GitHub by running `make serve`, alternatively `make docker-serve`. Please see the `Previewing your changes locally` section in [CONTRIBUTING.md](https://github.com/ESMValGroup/tutorial/blob/master/CONTRIBUTING.md) for installation instructions.
- [x] All code instructions have been tested.

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *

Closes #254 
Closes #204

### CODE REVIEW

**Comment by rswamina** [comment]
@SarahAlidoost - Should [Issue #204](https://github.com/ESMValGroup/ESMValTool_Tutorial/issues/204) be considered for this pull request or should we address that separately?

**Review by LisaBock — APPROVED** [review]
@SarahAlidoost Thanks! Looks fine.

Sorry I didn't make it earlier.

**Review by LisaBock — CHANGES_REQUESTED** [review]
@SarahAlidoost 
Sorry I just remember that you have to merge the recent main branch in this branch before we could merge that one in the main. There were some modifications (e.g. Compatibility to ESMValTool versions).

**Comment by SarahAlidoost** [comment]
> @SarahAlidoost Sorry I just remember that you have to merge the recent main branch in this branch before we could merge that one in the main. There were some modifications (e.g. Compatibility to ESMValTool versions).

@LisaBock there is no "merge conflict" in this pull request. If you merge this PR, GitHub will take care of merging the changes to the main branch.  Then this lesson will include both my changes and others' changes.

**Comment by LisaBock** [comment]
> 

I see. But you may want to update the compatibility to v.2.7.0 ?

**Comment by LisaBock** [comment]
> > @SarahAlidoost Sorry I just remember that you have to merge the recent main branch in this branch before we could merge that one in the main. There were some modifications (e.g. Compatibility to ESMValTool versions).
> 
> @LisaBock there is no "merge conflict" in this pull request. If you merge this PR, GitHub will take care of merging the changes to the main branch. Then this lesson will include both my changes and others' changes.

@SarahAlidoost  I see. But you may want to update the compatibility to v.2.7.0 ?

**Comment by SarahAlidoost** [comment]
> @LisaBock there is no "merge conflict" in this pull request. If you merge this PR, GitHub will take care of merging the changes to the main branch. Then this lesson will include both my changes and others' changes.

hmmm, let's keep it consistent with the rest of the lessons i.e. 2.6. The goal was to test the lesson for 2.6. I haven't tested it for 2.7 since it is recently released.

**Comment by LisaBock** [comment]
> > @LisaBock there is no "merge conflict" in this pull request. If you merge this PR, GitHub will take care of merging the changes to the main branch. Then this lesson will include both my changes and others' changes.
> 
> hmmm, let's keep it consistent with the rest of the lessons i.e. 2.6. The goal was to test the lesson for 2.6. I haven't tested it for 2.7 since it is recently released.

It says now episode v2.4 in the main. So you have to update it anyway...

**Comment by SarahAlidoost** [comment]
> > > @LisaBock there is no "merge conflict" in this pull request. If you merge this PR, GitHub will take care of merging the changes to the main branch. Then this lesson will include both my changes and others' changes.
> > 
> > 
> > hmmm, let's keep it consistent with the rest of the lessons i.e. 2.6. The goal was to test the lesson for 2.6. I haven't tested it for 2.7 since it is recently released.
> 
> It says now episode v2.4 in the main. So you have to update it anyway...

I will fix it :)

**Comment by SarahAlidoost** [comment]
@LisaBock sorry for the late fix. I changed 2.4 to 2.7. The github action is broken here. I fixed it in pull request #267

**Review by LisaBock — APPROVED** [review]
Thanks @SarahAlidoost! Looks good to me.

**Pull request merged**
