### PR TITLE
Add instruction to serve the site locally

### PR DESCRIPTION
**Pull request by stefsmeets**
I ran into some issues getting the tutorial to serve locally, so I used the instructions from #35. I suggest adding this little snippet to the `readme.md`.

### CODE REVIEW

**Comment by stefsmeets** [comment]
I just realized this is in the `contributing.md`, not the first place I would look for instructions to be honest.

**Comment by Peter9192** [comment]
Well, most people will not need to build the tutorial locally. And the README *does* refer to the contributing guidelines for those who are interested. So I don't think there's much more we can do. Perhaps add a note to the README like so:

The tutorial is hosted on .... (link). If you want to build it locally, please follow the instructions in contributing.md.

**Comment by stefsmeets** [comment]
This readme will only be seen by developers. The contributing.md is typically for how to make PRs and code style etc, not necessarily build instructions. In my opinion build instructions should be highlighed in the readme.

**Review by SarahAlidoost — CHANGES_REQUESTED** [review]
@stefsmeets thank you. I see that the pull request template is removed from this PR. The template and especially the first two items in the checklist are meant to help you and other contributors. 
Regarding this pull request, I suggest adding a version of @Peter9192 suggestion to the first section in the readme as:
"The tutorial is hosted on .... (link). If you want to contribute to lesson developments, please see the section contributing."  
We don't add the specific section of  "Previewing your changes locally" to the readme. The reason is that contributors should first read guides in contributing before making any changes.

**Pull request closed without merging**
