### PR TITLE
Update episode 10 for using esmvaltool 2.7

### LINKED ISSUE #255: updating lesson Debugging to 2.6
check the lesson "Debugging" and update it if needed.

### PR DESCRIPTION
**Pull request by SarahAlidoost**
# Pull Request checklist

We appreciate your time and effort to improve the tutorial. Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution.

* * *

## Before you start

- [x] Read [CONTRIBUTING.md](https://github.com/ESMValGroup/tutorial/blob/master/CONTRIBUTING.md).
- [x] Create an [issue](https://github.com/ESMValGroup/tutorial/issues) to discuss your idea. This allows your contributions to be incorporated into the tutorial.

## Tasks

- [x] Give this pull request a descriptive title.
- [x] If you are contributing to existing lesson materials, please make sure the content conforms to the `Lesson development` section in [CONTRIBUTING.md](https://github.com/ESMValGroup/tutorial/blob/master/CONTRIBUTING.md) and does not contain any spelling or grammatical errors.
- [x] If you are making a new episode, please make sure the content conforms to the `Lesson organization` and `Lesson formatting` sections in [CONTRIBUTING.md](https://github.com/ESMValGroup/tutorial/blob/master/CONTRIBUTING.md) and does not contain any spelling or grammatical errors.
- [x] Preferably Codacy checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why.
- [x] Preview changes on your machine before pushing them to GitHub by running `make serve`, alternatively `make docker-serve`. Please see the `Previewing your changes locally` section in [CONTRIBUTING.md](https://github.com/ESMValGroup/tutorial/blob/master/CONTRIBUTING.md) for installation instructions.
- [x] All code instructions have been tested.

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *

Closes #255

### CODE REVIEW

**Review by LisaBock — CHANGES_REQUESTED** [review]
Thanks @SarahAlidoost ! Looks all great!

Please update with the current main branch. Then we could merge.

**Comment by SarahAlidoost** [comment]
> Thanks @SarahAlidoost ! Looks all great!
> 
> Please update with the current main branch. Then we could merge.

@LisaBock there is no "merge conflict" in this pull request. If you merge this PR, GitHub will take care of merging the changes to the main branch. Then this lesson will include both my changes and others' changes.

**Comment by LisaBock** [comment]
> > Thanks @SarahAlidoost ! Looks all great!
> > Please update with the current main branch. Then we could merge.
> 
> @LisaBock there is no "merge conflict" in this pull request. If you merge this PR, GitHub will take care of merging the changes to the main branch. Then this lesson will include both my changes and others' changes.

@SarahAlidoost I see. But you may want to update the compatibility to v.2.7.0 ?

**Comment by SarahAlidoost** [comment]
> > > Thanks @SarahAlidoost ! Looks all great!
> > > Please update with the current main branch. Then we could merge.
> > 
> > 
> > @LisaBock there is no "merge conflict" in this pull request. If you merge this PR, GitHub will take care of merging the changes to the main branch. Then this lesson will include both my changes and others' changes.
> 
> @SarahAlidoost I see. But you may want to update the compatibility to v.2.7.0 ?

hmmm, let's keep it consistent with the rest of the lessons i.e. 2.6. The goal was to test the lesson for 2.6. I haven't tested it for 2.7 since it is recently released.

**Comment by SarahAlidoost** [comment]
@LisaBock I changed 2.4 to 2.7. The github action was broken here. I fixed it!

**Review by LisaBock — APPROVED** [review]
Thanks @SarahAlidoost! Looks good to me.

**Pull request merged**
