### PR TITLE
Fix episode 4 and 5 regarding output of the recipes

### LINKED ISSUE #134: Output of recipe in episode 4 for v2.0.0
The current output (stdout/log files/settings) of running the example recipe in episode 4 uses ESMValTool v2.0.0b9 . It would be nice if the output would reflect the version end users will install so their output and the tutorials output is as similar as possible.

### PR DESCRIPTION
**Pull request by SarahAlidoost**
# Pull Request checklist

We appreciate your time and effort to improve the tutorial. Please keep in mind that lesson maintainers are volunteers and it may be some time before they can respond to your contribution.

* * *

## Before you start

- [x] Read [CONTRIBUTING.md](https://github.com/ESMValGroup/tutorial/blob/master/CONTRIBUTING.md).
- [x] Create an [issue](https://github.com/ESMValGroup/tutorial/issues) to discuss your idea. This allows your contributions to be incorporated into the tutorial.

## Tasks

- [x] Give this pull request a descriptive title.
- [ ] If you are contributing to existing lesson materials, please make sure the content conforms to the `Lesson development` section in [CONTRIBUTING.md](https://github.com/ESMValGroup/tutorial/blob/master/CONTRIBUTING.md) and does not contain any spelling or grammatical errors.
- [ ] If you are making a new episode, please make sure the content conforms to the `Lesson organization` and `Lesson formatting` sections in [CONTRIBUTING.md](https://github.com/ESMValGroup/tutorial/blob/master/CONTRIBUTING.md) and does not contain any spelling or grammatical errors.
- [ ] Preferably Codacy checks pass. Status can be seen below your pull request. If there is an error, click the link to find out why.
- [x] Preview changes on your machine before pushing them to GitHub by running `make serve`, alternatively `make docker-serve`. Please see the `Previewing your changes locally` section in [CONTRIBUTING.md](https://github.com/ESMValGroup/tutorial/blob/master/CONTRIBUTING.md) for installation instructions.
- [x] All code instructions have been tested.

If you need help with any of the tasks above, please do not hesitate to ask by commenting in the issue or pull request.

* * *

Closes #134

### CODE REVIEW

**Review by Peter9192 — DISMISSED** [review]
Thanks for updating @SarahAlidoost !
I think overall these episodes need a bigger overhaul (see #142), but this PR makes sure the current version at least is up to date, also in the git history of the tutorial.

**Comment by Peter9192** [comment]
Maybe we need to fix the test before merging though

**Comment by Peter9192** [comment]
See here: https://github.com/ESMValGroup/ESMValTool_Tutorial/blob/75763d6eb288819b21a46f3cea5d3612432e7406/.github/workflows/recipes.yml#L47

**Comment by SarahAlidoost** [comment]
> See here:
> 
> https://github.com/ESMValGroup/ESMValTool_Tutorial/blob/75763d6eb288819b21a46f3cea5d3612432e7406/.github/workflows/recipes.yml#L47

Thanks, I fixed the path.

**Review by Peter9192 — APPROVED** [review]
Test passes now, thanks!

**Pull request merged**
